wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721516716
    t:
      1:
      - 30
      - 55
      2:
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 13
      - 23
      4: 3.10.14
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
    framework: keras
