run_config:
  agent_name: rodent
  algo_name: dmpo
  task_name: escape-bowl
  run_name: rodent-bowl

obs_network:
  # observation network params
  use_visual_network: true
  visual_feature_size: 16

learner_network:
  # network factory params
  use_intention: true
  encoder_layer_sizes: [1024, 1024]
  decoder_layer_sizes: [1024, 1024]
  critic_layer_sizes: [1024, 1024, 1024]
  intention_size: 60

env_params:
  # env params
  num_replay_servers: 1
  separate_replay_servers: false
  num_actors: 401

learner_params:
  # learner parameters
  batch_size: 256
  discount: 0.99
  policy_optimizer_lr: 1e-4
  critic_optimizer_lr: 1e-4
  dual_optimizer_lr: 1e-3
  checkpoint_to_load: /root/vast/scott-yang/flybody/training/ray-rodent-escape-bowl-ckpts/bowl_transfer_t2/checkpoints/dmpo_learner/ckpt-115
  load_decoder_only: false
  froze_decoder: true # whether the decoder is trainable or not.

eval_params:
  # evaluator params
  eval_average_over: 10 # walk only 