run_config:
  agent_name: humanoid 
  algo_name: dmpo 
  task_name: humanoid_imitation # for selecting tasks dictionary (Most Important)
  run_name: multi-clip_imitation # for wandb

obs_network:
  # observation network params
  use_visual_network: false
  visual_feature_size: 0

learner_network:
  # network factory params
  use_intention: false
  policy_layer_sizes: [1024, 1024, 1024]
  critic_layer_sizes: [512,1024,1024,1024]
  intention_size: 0
  # if specified, this is the mid_level_encoder size, and the encoder layer size is the high level size
  use_multi_encoder: false
  mid_layer_sizes: 
  high_level_intention_size: 

env_params:
  # env params
  num_replay_servers: 1
  separate_replay_servers: false
  num_actors: 40

learner_params:
  # learner parameters
  batch_size: 256
  discount: 0.97
  policy_optimizer_lr: 1e-4
  critic_optimizer_lr: 1e-4
  dual_optimizer_lr: 1e-3
  checkpoint_to_load:
  load_decoder_only: false
  froze_decoder: false # whether the decoder is trainable or not.
  froze_mid_level_encoder: false

eval_params:
  # evaluator params
  eval_average_over: 10