run_config:
  agent_name: mouse
  algo_name: dmpo
  task_name: mouse_reach
  run_name:  mouse-forelimb-reach
  actuator_type: torque

obs_network:
  # observation network params
  use_visual_network: false
  visual_feature_size: 0
  
policy_network_params:
  num_dimensions: 10  # Example value
  tanh_mean: true
  init_scale: 0.1
  fixed_scale: false
  use_tfd_independent: false

learner_network:
  # need to be consistent with the rest of the task if we want to task swichting
  policy_layer_sizes: [512,512,512,512]
  use_intention: false
  encoder_layer_sizes: [1024, 1024]
  decoder_layer_sizes: [1024, 1024]
  critic_layer_sizes: [1024, 1024, 1024]
  intention_size: 60
  use_multi_decoder: False

learner_params:
  # learner parameters
  batch_size: 256
  policy_optimizer_lr: 1e-4
  critic_optimizer_lr: 1e-4
  dual_optimizer_lr: 1e-3
  # checkpoint system
  load_decoder_only: false
  checkpoint_to_load:
  # evaluator params
  eval_average_over: 500
  discount: .95

env_params:
  num_actors: 25
  num_replay_servers: 2

eval_params:
  eval_average_over: 500