run_config:
  agent_name: rodent
  algo_name: dmpo
  task_name: escape-bowl
  run_name: rodent-bowl

obs_network:
  # observation network params
  use_visual_network: true
  visual_feature_size: 16

learner_network:
  # network factory params
  use_intention: true
  encoder_layer_sizes: [512, 512, 512]
  decoder_layer_sizes: [1024, 1024]
  critic_layer_sizes: [1024,1024,512,512,512]
  intention_size: 60
  # if specified, this is the mid_level_encoder size, and the encoder layer size is the high level size
  use_multi_encoder: true
  mid_layer_sizes: [512, 1024] 
  high_level_intention_size: 45

env_params:
  # env params
  num_replay_servers: 1
  separate_replay_servers: false
  num_actors: 530

learner_params:
  # learner parameters
  batch_size: 256
  discount: 0.97
  policy_optimizer_lr: 1e-4
  critic_optimizer_lr: 1e-4
  dual_optimizer_lr: 1e-3
  checkpoint_to_load: /root/vast/scott-yang/flybody/training/ray-rodent-escape-bowl-ckpts/4aa76af8-7634-11ef-9951-da7a3e4c64c0/checkpoints/dmpo_learner/ckpt-2
  load_decoder_only: false
  froze_decoder: true # whether the decoder is trainable or not.

eval_params:
  # evaluator params
  eval_average_over: 10 # walk only 