agent_name: rodent
algo_name: dmpo
task_name: general
run_name: four_tasks

# observation network params
use_visual_network: true
visual_feature_size: 10 # eventually we want to do 16

# network factory params
use_intention: true
encoder_layer_sizes: [1024, 1024]
decoder_layer_sizes: [1024, 1024]
critic_layer_sizes: [1024, 1024, 1024]
intention_size: 60

# env params
termination_error_threshold:
num_replay_servers: 1 # in multi task, this indicate the number of replay server for each sub tasks.
separate_replay_servers: false
num_actors: 401
actors_envs: # Calculation based on the disparity of sps in stepping.
  run-gaps: 105
  maze-forage: 128
  escape-bowl: 128
  two-taps: 40
# learner parameters
batch_size: 256
policy_optimizer_lr: 1e-4
critic_optimizer_lr: 1e-4
dual_optimizer_lr: 1e-3
checkpoint_to_load: /root/vast/scott-yang/vnl_ray/training/ray-rodent-run-gaps-ckpts/run-gaps-decoder-transfer/checkpoints/dmpo_learner/ckpt-35
load_decoder_only: false
froze_decoder: true # whether the decoder is trainable or not.

# evaluator params
eval_average_over: 10 # walk only 