agent_name: rodent
algo_name: dmpo
task_name: run-gaps
run_name: gaps

# observation network params
use_visual_network: true
visual_feature_size: 10

# network factory params
use_intention: true
encoder_layer_sizes: [1024, 1024]
decoder_layer_sizes: [1024, 1024]
critic_layer_sizes: [1024, 1024, 1024]
intention_size: 60
num_replay_servers: 1
num_actors: 162

# env params
termination_error_threshold:

# learner parameters
batch_size: 256
policy_optimizer_lr: 1e-4
critic_optimizer_lr: 1e-4
dual_optimizer_lr: 1e-3
load_decoder_only: true
checkpoint_to_load: /root/vast/scott-yang/vnl_ray/training/ray-rodent-imitation_rodent-ckpts/mc-correct-2/checkpoints/dmpo_learner/ckpt-92

# evaluator params
eval_average_over: 10 # walk only 