agent_name: rodent
algo_name: dmpo
task_name: general
run_name: four_tasks

# observation network params
use_visual_network: true
visual_feature_size: 16

# network factory params
use_intention: true
encoder_layer_sizes: [1024, 1024]
decoder_layer_sizes: [1024, 1024]
critic_layer_sizes: [1024, 1024, 1024]
intention_size: 60

# env params
termination_error_threshold:
num_replay_servers: 1 # in multi task, this indicate the number of replay server for each sub tasks.
separate_replay_servers: false
num_actors: 400
actors_envs: # Calculation based on the disparity of sps in stepping.
  run-gaps: 5
  maze-forage: 250
  escape-bowl: 5
  two-taps: 140
# learner parameters
batch_size: 256
policy_optimizer_lr: 1e-4
critic_optimizer_lr: 1e-4
dual_optimizer_lr: 1e-3
discount: 0.99
checkpoint_to_load: /root/vast/scott-yang/flybody/training/ray-rodent-escape-bowl-ckpts/bowl_transfer_t2/checkpoints/dmpo_learner/ckpt-115
load_decoder_only: false
froze_decoder: true # whether the decoder is trainable or not.

# evaluator params
eval_average_over: 10 # walk only 