agent_name: rodent
algo_name: dmpo
task_name: general
run_name: rodent
batch_size: 2048
policy_layer_sizes: [512,512,512,512]
critic_layer_sizes: [512,512,512,512]
num_actors: 0 # total number of actors
actors_envs:
  run-gaps: 67
  maze-forage: 67
  escape-bowl: 67
  two-taps: 67
checkpoint_to_load: #/root/vast/scott-yang/flybody/training/ray-rodent-escape-bowl-ckpts/1c0f2602-4df5-11ef-a59a-2ae1cc4cdff5/checkpoints/dmpo_learner/ckpt-87
group_name: generalist
kickstart_teacher_cps_path: /root/vast/scott-yang/flybody/training/ray-rodent-escape-bowl-ckpts/25422bcc-5389-11ef-93c8-2ae1cc4cdff5/snapshots/policy-only-no-obs-network-33
kickstart_epsilon: 0.5