agent_name: rodent
algo_name: dmpo
task_name: two-taps
run_name: rodent-two-taps
batch_size: 512
policy_layer_sizes: [512, 512, 512, 512]
critic_layer_sizes: [512, 512, 512, 256]
num_actors: 58
group_name: rodent-maze-forage-v1
checkpoint_to_load:
