agent_name: rodent
algo_name: dmpo
training_type: imitation
task_name: imitation_rodent
run_name: rodent_imitation
batch_size: 2048
encoder_layer_sizes: [1024, 1024]
decoder_layer_sizes: [1024, 1024]
critic_layer_sizes: [1024, 1024, 1024]
latent_layer_sizes: 60
num_replay_servers: 1
num_actors: 595
group_name: rodent-imitation

# for some reason only abs path works here
ref_traj_path: /root/vast/scott-yang/flybody/clips/all_snippets.h5
checkpoint_to_load:
kickstart_teacher_cps_path:
kickstart_epsilon: