agent_name: rodent
algo_name: dmpo
task_name: imitation
run_name: rodent_imitation
batch_size: 512
policy_layer_sizes: [512, 512, 512]
critic_layer_sizes: [512, 512, 512]
num_actors: 150
group_name: rodent-imitation

# for some reason only abs path works here
ref_traj_path: "/root/talmolab-smb/kaiwen/flybody/clips/only_walk_35.h5"
checkpoint_to_load: "/root/talmolab-smb/kaiwen/flybody/policy/intention_single_policy-46"
