agent_name: rodent
algo_name: dmpo
task_name: imitation_rodent
run_name: imitation_rodent

# network factory params
use_intention: true
encoder_layer_sizes: [1024, 1024]
decoder_layer_sizes: [1024, 1024]
critic_layer_sizes: [1024, 1024, 1024]
intention_size: 60
num_replay_servers: 2
num_actors: 270

# env params
termination_error_threshold: 0.2 # see notebooks/env_testing 0.13 starting

# learner parameters
batch_size: 256
policy_optimizer_lr: 1e-4
critic_optimizer_lr: 1e-4
dual_optimizer_lr: 1e-3
ref_traj_path: /root/vast/scott-yang/flybody/clips/all_snippets.h5 #walk_only_clips.h5
load_decoder_only: false
checkpoint_to_load: /root/vast/scott-yang/flybody/training/ray-rodent-imitation_rodent-ckpts/mc-correct-2/checkpoints/dmpo_learner/ckpt-92

# evaluator params
eval_average_over: 500 # walk only 
# as we have 842 clips, in avg this should gives us a good est