agent_name: rodent
algo_name: dmpo
task_name: general
run_name: rodent
batch_size: 4096
policy_layer_sizes: [1024,1024,1024,1024]
critic_layer_sizes: [1024,512,512,256]
num_actors: 0 # total number of actors
actors_envs:
  run-gaps: 45
  maze-forage: 45
  escape-bowl: 44
  two-taps: 44
checkpoint_to_load:
group_name: generalist
