agent_name: rodent
algo_name: dmpo
training_type: imitation
task_name: imitation
run_name: rodent_imitation
batch_size: 128
policy_layer_sizes: [1024, 1024]
critic_layer_sizes: [1024, 1024, 1024]
latent_layer_sizes: 60
num_actors: 60 # roden job memory requirement is great
group_name: rodent-imitation

# for some reason only abs path works here
ref_traj_path: "/root/talmolab-smb/kaiwen/flybody/clips/all_snippets.h5"
checkpoint_to_load:
