agent_name: humanoid
algo_name: dmpo
task_name: imitation
run_name: humanoid_imitation
batch_size: 128
policy_layer_sizes: [1024, 1024]
critic_layer_sizes: [1024, 1024, 1024]
latent_layer_sizes: 60
num_actors: 100
group_name: basic-imitation

# for some reason only abs path works here
ref_traj_path: "/root/talmolab-smb/kaiwen/flybody/clips/cmu_2020_dfe3e9e0.h5"
checkpoint_to_load: "/root/talmolab-smb/kaiwen/flybody/policy/humanoid_policy-43"
